name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  sonarqube:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'  # Change this to the appropriate .NET version

      - name: Build
        run: dotnet build --configuration Release

      #- name: Test
       # run: dotnet test --configuration Release

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # Configure SonarQube properties
          #echo "sonar.projectKey=sonartest" >> sonar-project.properties
          #echo "sonar.projectName=sonartest" >> sonar-project.properties
          #echo "sonar.sources=." >> sonar-project.properties
          #echo "sonar.host.url=${{secrets.SONAR_HOST_URL}}" >> sonar-project.properties  # Update with your SonarQube server URL
          #echo "sonar.login=${{ secrets.SONAR_TOKEN }}" >> sonar-project.properties

          # Run SonarScanner for .NET
          # dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"sonartest" /d:sonar.host.url="${{secrets.SONAR_HOST_URL}}" /d:sonar.login="${{ secrets.SONAR_TOKEN}}"
          dotnet build --configuration Release
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
